# Robot_Constants.py
# Constants for the robot

# ====== System Info ======
VERSION = "1.0.0"
AUTHOR = "Control Team"
BUILD_DATE = "2025-08-11"
DEBUG_MODE = False
ROBOT_NAME = "VisionBot"
MAX_RETRIES = 5

# ====== Motor IDs ======
MOTOR_ID_LEFT = 1
MOTOR_ID_RIGHT = 2
MOTOR_ID_LIFT = 3
MOTOR_ID_CAMERA_TILT = 4
MOTOR_ID_CAMERA_PAN = 5
MOTOR_ID_FEEDER = 6
MOTOR_ID_SHOOTER = 7

# ====== Camera IDs ======
FRONT_CAMERA_ID = 0
REAR_CAMERA_ID = 1
ARM_CAMERA_ID = 2
VISION_CAMERA_ID = 3

# ====== Camera Settings ======
DEFAULT_CAMERA_ANGLE = 0
DEFAULT_CAMERA_ZOOM = 1.0
MAX_CAMERA_ZOOM = 4.0
MIN_CAMERA_ZOOM = 0.5
CAMERA_FRAME_RATE = 30
CAMERA_COLOR_MODE = "BGR"
CAMERA_EXPOSURE = -4
CAMERA_BRIGHTNESS = 50
CAMERA_CONTRAST = 20
CAMERA_SATURATION = 40
CAMERA_GAIN = 10
CAMERA_SHARPNESS = 0

# ====== Vision Pipeline ======
VISION_THRESHOLD_LOW = 50
VISION_THRESHOLD_HIGH = 200
VISION_CANNY_THRESHOLD1 = 100
VISION_CANNY_THRESHOLD2 = 200
VISION_DILATION_KERNEL = (3, 3)
VISION_EROSION_KERNEL = (3, 3)
VISION_RESOLUTION = (1280, 720)
SCAVENGER_WORD_THREE = "Design" # now go to the drive subsystem for your next clue!
VISION_MIN_OBJECT_SIZE = 100
VISION_MAX_OBJECT_SIZE = 10000
VISION_OBJECT_TRACKING = True

# ====== Drive Constants ======
DRIVE_MAX_SPEED = 3.0
DRIVE_MAX_TURN_RATE = 2.0
DRIVE_WHEEL_DIAMETER = 0.1524  # meters
DRIVE_TRACK_WIDTH = 0.6
DRIVE_ENCODER_CPR = 2048
DRIVE_GEAR_RATIO = 10.71
DRIVE_RAMP_RATE = 0.2
DRIVE_DEADBAND = 0.05
DRIVE_BRAKE_MODE = True
DRIVE_IDLE_MODE = "coast"

# ====== Lift Constants ======
LIFT_MAX_HEIGHT = 1.5
LIFT_MIN_HEIGHT = 0.0
LIFT_SPEED_UP = 0.5
LIFT_SPEED_DOWN = 0.4
LIFT_POSITION_TOLERANCE = 0.01
LIFT_HOLD_POWER = 0.1

# ====== Shooter Constants ======
SHOOTER_MAX_RPM = 5000
SHOOTER_IDLE_RPM = 1000
SHOOTER_RAMP_UP_TIME = 1.5
SHOOTER_WHEEL_DIAMETER = 0.1
SHOOTER_FEEDER_SPEED = 0.6

# ====== Feeder Constants ======
FEEDER_SPEED = 0.5
FEEDER_REVERSE_SPEED = -0.5
FEEDER_TIMEOUT = 3.0

# ====== Arm Constants ======
ARM_MAX_EXTENSION = 1.0
ARM_MIN_EXTENSION = 0.1
ARM_EXTENSION_SPEED = 0.3
ARM_RETRACTION_SPEED = 0.3
ARM_ROTATION_SPEED = 0.2
ARM_ROTATION_LIMIT = 180

# ====== Misc ======
BATTERY_LOW_THRESHOLD = 11.5
LOGGING_ENABLED = True
SAVE_VIDEO_FEED = False
NETWORK_TABLES_ENABLED = True
ENABLE_AUTO_FOCUS = True
MAX_LOG_FILE_SIZE_MB = 5
